// Where a server's password lives on this Mac, and how ssh gets it out
// (remote.md §4).
//
// Everything here goes through `/usr/bin/security` rather than through
// Security.framework, and that is the design rather than the expedient. A
// keychain item's ACL trusts the program that CREATED it, so an item written by
// `security` is readable by `security` and Ledge's own code signature never
// enters the ACL at all. Re-signing the app therefore cannot lock it out of its
// own secrets, which is the failure locking.md §3 warns about for items created
// with `SecItemAdd` inside the app. Measured in a real bundle: every read is
// silent, with no `SecurityAgent` prompt, and a relaunch reads back what an
// earlier launch wrote.
//
// The other half of that fact is the cost, and remote.md §4 states it: anything
// running as this user can read the item with the same one command. That is the
// mode 600 key file `keyPath` already names, exactly, rather than something
// weaker or stronger.
//
// **The plaintext never leaves through this process.** ssh is pointed at the
// helper script below with `SSH_ASKPASS`, the helper calls `security` itself,
// and its stdout goes straight to ssh. Nothing in Bun reads a password back
// except `storePassword`, which reads the one it just wrote to check that it
// arrived.
import { chmod, rename, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { CLIENT_HOME, ensureClientHome } from "./clientHome";

// Fixed, not PATH-resolved, for the reason connections.ts fixes ssh's tools:
// these are spawned without a shell, and every macOS ships them here. xxd is
// the hex decoder the helper needs and has shipped with macOS as long as vim
// has.
export const SECURITY_PATH = "/usr/bin/security";
export const XXD_PATH = "/usr/bin/xxd";

/** The keychain service every stored server password is filed under. One
 * service, one item per connection id, so `security delete-generic-password`
 * takes exactly the same two arguments as the write. */
export const KEYCHAIN_SERVICE = "sh.ledge.app.server";

/** The helper ssh runs when it wants a password, written into the client home
 * at every launch (`ensureAskpass`). */
export const ASKPASS_PATH = join(CLIENT_HOME, "askpass.sh");

/** How the helper is told WHICH connection is being dialled. A connection id
 * and not a secret, so it costs nothing that it is visible in the environment
 * of the ssh process it is passed to. */
export const ASKPASS_ACCOUNT_ENV = "LEDGE_ASKPASS_ACCOUNT";

// --- pure core (unit-tested in secrets.test.ts) ------------------------------

/**
 * A password as the hex of its UTF-8 bytes, which is the form that is stored.
 *
 * Not obfuscation: it is what makes ONE decoding rule correct for every
 * password. `security find-generic-password -w` prints the value as text when
 * the bytes are printable ASCII and as hex when they are not, with nothing in
 * the output saying which happened — so a password containing "ä" comes back as
 * `70c3a4` and a password that IS "70c3a4" comes back the same. Storing hex
 * makes the stored value printable ASCII always, so the read is always hex,
 * always decoded, and never guessed at.
 */
export function toHex(text: string): string {
  return Array.from(new TextEncoder().encode(text))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/** The inverse, for the test that holds the round trip. The helper does this
 * with `xxd -r -p` rather than with this. */
export function fromHex(hex: string): string {
  const bytes = new Uint8Array(hex.length >> 1);
  for (let i = 0; i < bytes.length; i++) bytes[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return new TextDecoder().decode(bytes);
}

/**
 * The `SSH_ASKPASS` helper, as text.
 *
 * ssh runs this with the prompt as its argument and reads the first line of its
 * stdout as the password. The prompt is ignored: there is exactly one thing
 * this connection could be being asked for, and a helper that parsed English
 * would be a helper that answered the wrong question after an OpenSSH release.
 *
 * It reads the keychain itself, which is the point. A password handed to this
 * script would have to exist in Bun's memory and on a pipe first; this way the
 * secret's whole path is keychain to stdout to ssh.
 *
 * A missing item exits non-zero and prints nothing, which ssh reports as a
 * failed authentication rather than as an empty password it then sends.
 */
export function askpassScript(): string {
  return `#!/bin/sh
# Ledge's SSH_ASKPASS helper. Generated by src/bun/secrets.ts; edits are lost
# at the next launch. What it is for: docs/contributor/remote.md §4.
set -u
[ -n "\${${ASKPASS_ACCOUNT_ENV}:-}" ] || exit 1
hex=$(${SECURITY_PATH} find-generic-password -s ${KEYCHAIN_SERVICE} -a "\$${ASKPASS_ACCOUNT_ENV}" -w 2>/dev/null) || exit 1
[ -n "\$hex" ] || exit 1
printf '%s' "\$hex" | ${XXD_PATH} -r -p
`;
}

// --- the keychain, and the file ----------------------------------------------

/**
 * Store one connection's password, replacing whatever was there.
 *
 * Fed on stdin rather than passed as `-w <password>`: `security`'s own usage
 * text calls the argument form insecure, and it is right that an argv is the
 * wrong place for a secret even when the kernel keeps other users out of it
 * (the same rule §10 applies to profiles). `-w` LAST makes it prompt, and it
 * prompts twice to confirm, so the value goes in twice.
 *
 * Read back before this returns true. A mismatched confirmation makes
 * `security` store an EMPTY password and still exit 0, so its exit code is not
 * evidence on its own, and a silently empty password would reach the user as a
 * server that rejects a password they can see is right.
 */
export async function storePassword(id: string, password: string): Promise<{ ok: boolean; error: string }> {
  const hex = toHex(password);
  try {
    const write = Bun.spawn([SECURITY_PATH, "add-generic-password", "-U", "-s", KEYCHAIN_SERVICE, "-a", id, "-l", LABEL, "-j", COMMENT, "-w"], {
      stdin: "pipe",
      stdout: "ignore",
      stderr: "ignore",
    });
    write.stdin.write(`${hex}\n${hex}\n`);
    await write.stdin.end();
    if ((await write.exited) !== 0) return { ok: false, error: KEYCHAIN_REFUSED };
  } catch (err) {
    return { ok: false, error: `Could not reach the keychain (${reason(err)}).` };
  }
  const stored = await readPassword(id);
  if (stored !== password) return { ok: false, error: KEYCHAIN_REFUSED };
  return { ok: true, error: "" };
}

/** Whether a password is stored for this connection, WITHOUT reading it. No
 * `-w`, so `security` prints the item's attributes and never its data: asking
 * "is there one" must not be a way to get one. */
export async function hasPassword(id: string): Promise<boolean> {
  try {
    const p = Bun.spawn([SECURITY_PATH, "find-generic-password", "-s", KEYCHAIN_SERVICE, "-a", id], {
      stdout: "ignore",
      stderr: "ignore",
    });
    return (await p.exited) === 0;
  } catch {
    return false;
  }
}

/**
 * Drop a connection's password, if it has one.
 *
 * Silent about a missing item, because every caller is removing or re-keying a
 * connection and "there was nothing to delete" is a success for both.
 */
export async function forgetPassword(id: string): Promise<void> {
  try {
    const p = Bun.spawn([SECURITY_PATH, "delete-generic-password", "-s", KEYCHAIN_SERVICE, "-a", id], {
      stdout: "ignore",
      stderr: "ignore",
    });
    await p.exited;
  } catch {
    // A keychain that cannot be reached costs a stale item, not the removal of
    // the connection the caller is in the middle of.
  }
}

/**
 * Replace what is stored for a connection, and hand back the way to put the
 * old value back.
 *
 * `next` is a password to store or null to leave nothing stored. The caller
 * dials between the two — the dial is what proves a password works, and that
 * means the new one has to be in the keychain before ssh runs — so a dial that
 * fails needs the previous state back exactly.
 *
 * This is the only place in the app that reads a stored password into memory,
 * and `restore` is the whole reason: without the old value there is no way to
 * undo, and an edit that mistyped a password would destroy the working one on
 * its way to reporting the failure. It is the user's own secret, in the user's
 * own process, for as long as one ssh takes to fail.
 */
export async function swapPassword(
  id: string,
  next: string | null,
): Promise<{ error: string; restore: () => Promise<void> }> {
  const before = (await hasPassword(id)) ? await readPassword(id) : null;
  const restore = async (): Promise<void> => {
    if (before === null) await forgetPassword(id);
    else await storePassword(id, before);
  };
  if (next === null) {
    await forgetPassword(id);
    return { error: "", restore };
  }
  const stored = await storePassword(id, next);
  // Nothing was replaced when the write failed, so there is nothing to undo,
  // and handing back a restore that rewrites the old value would be a second
  // keychain write on a keychain that just refused one.
  if (!stored.ok) return { error: stored.error, restore: async () => {} };
  return { error: "", restore };
}

/**
 * Write the helper into the client home and return its path.
 *
 * Rewritten at every launch rather than written once, so a script from an older
 * version is replaced rather than trusted. 0700 because it is executable and
 * nobody but this user has any business running it; via a temp file and a
 * rename, like every other write in the app home, so a half-written script is
 * never the one ssh finds.
 */
export async function ensureAskpass(): Promise<string> {
  await ensureClientHome();
  const tmp = `${ASKPASS_PATH}.tmp-${process.pid}`;
  try {
    await writeFile(tmp, askpassScript(), "utf8");
    await chmod(tmp, 0o700);
    await rename(tmp, ASKPASS_PATH);
  } catch (err) {
    await unlink(tmp).catch(() => {});
    throw err;
  }
  return ASKPASS_PATH;
}

// --- inside -------------------------------------------------------------------

// What Keychain Access shows for these items. The label is the row, the comment
// is the answer to "why is this one gibberish" for anyone who opens it.
const LABEL = "Ledge server password";
const COMMENT = "Stored by Ledge for one server connection, as the hex of the password's UTF-8 bytes.";

const KEYCHAIN_REFUSED = "The keychain would not store that password.";

/** The one read in this file, and it exists only to check a write. */
async function readPassword(id: string): Promise<string | null> {
  try {
    const p = Bun.spawn([SECURITY_PATH, "find-generic-password", "-s", KEYCHAIN_SERVICE, "-a", id, "-w"], {
      stdout: "pipe",
      stderr: "ignore",
    });
    const out = await new Response(p.stdout).text();
    if ((await p.exited) !== 0) return null;
    return fromHex(out.trim());
  } catch {
    return null;
  }
}

function reason(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}
