// Where a server's password lives on this Mac, and how ssh gets it out
// (remote.md §4).
//
// Everything here goes through `/usr/bin/security` rather than through
// Security.framework. The item's ACL then names that binary and not Ledge.
// Re-signing the app therefore cannot lock it out of its own secrets, the
// failure locking.md §3 warns about for items created with `SecItemAdd`. The
// cost is that any process running as this user reads the item with that one
// command, the same reach the mode 600 key file `keyPath` already names.
//
// The plaintext does not pass through this process on the way to ssh. The
// helper script below reads the keychain itself under `SSH_ASKPASS`, and its
// stdout goes straight to ssh. `storePassword` and `swapPassword` are the two
// calls here that read a password back.
import { chmod, rename, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { CLIENT_HOME, ensureClientHome } from "./clientHome";

// Fixed, not PATH-resolved, for the reason connections.ts fixes ssh's tools:
// these are spawned without a shell. `security` is part of macOS, and xxd, the
// hex decoder the helper runs, has shipped with macOS as long as vim has.
export const SECURITY_PATH = "/usr/bin/security";
export const XXD_PATH = "/usr/bin/xxd";

/** The keychain service every stored server password is filed under. One
 * service, one item per connection id, so `security delete-generic-password`
 * takes exactly the same two arguments as the write. */
export const KEYCHAIN_SERVICE = "sh.ledge.app.server";

/** The helper ssh runs when it wants a password, written into the client home
 * before a password connection is dialled (`ensureAskpass`). */
export const ASKPASS_PATH = join(CLIENT_HOME, "askpass.sh");

/** Tells the helper which connection is being dialled. The value is a
 * connection id and not a secret, so it is safe in the environment of the ssh
 * process it is passed to. */
export const ASKPASS_ACCOUNT_ENV = "LEDGE_ASKPASS_ACCOUNT";

// --- pure core (unit-tested in secrets.test.ts) ------------------------------

/**
 * A password as the hex of its UTF-8 bytes, which is the form that is stored.
 *
 * Not obfuscation: hex makes one decoding rule right for every password.
 * `security find-generic-password -w` prints a value as text when its bytes
 * are printable ASCII and as hex when they are not, with nothing in the output
 * saying which happened, so the password "ä" and the password "c3a4" both come
 * back as `c3a4`. Storing hex keeps the read always hex, and always decoded.
 */
export function toHex(text: string): string {
  return Array.from(new TextEncoder().encode(text))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/** The inverse of `toHex`. `readPassword` decodes with it, and the round-trip
 * test in secrets.test.ts holds the pair. The helper script decodes with
 * `xxd -r -p` instead. */
export function fromHex(hex: string): string {
  const bytes = new Uint8Array(hex.length >> 1);
  for (let i = 0; i < bytes.length; i++) bytes[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return new TextDecoder().decode(bytes);
}

/**
 * The `SSH_ASKPASS` helper, as text.
 *
 * ssh runs the script with the prompt as its argument and reads the first line
 * of its stdout as the password. The script ignores the prompt: a password is
 * the only thing this connection is asked for, and parsing the English would
 * break at an OpenSSH wording change. The script reads the keychain itself, so
 * the secret never sits in Bun's memory or on a pipe (remote.md §4). A missing
 * item exits non-zero and prints nothing, which ssh reports as a failed
 * authentication rather than sending an empty password.
 */
export function askpassScript(): string {
  return `#!/bin/sh
# Ledge's SSH_ASKPASS helper. Generated by src/bun/secrets.ts; edits are lost
# at the next launch. What it is for: docs/contributor/remote.md §4.
set -u
[ -n "\${${ASKPASS_ACCOUNT_ENV}:-}" ] || exit 1
hex=$(${SECURITY_PATH} find-generic-password -s ${KEYCHAIN_SERVICE} -a "\$${ASKPASS_ACCOUNT_ENV}" -w 2>/dev/null) || exit 1
[ -n "\$hex" ] || exit 1
printf '%s' "\$hex" | ${XXD_PATH} -r -p
`;
}

// What Keychain Access shows for these items. The label names the row, and the
// comment tells anyone who opens it why the value is hex.
const LABEL = "Ledge server password";
const COMMENT = "Stored by Ledge for one server connection, as the hex of the password's UTF-8 bytes.";

/**
 * The whole `add-generic-password` command, as the one line `security -i`
 * reads off its stdin.
 *
 * Interactive mode is used because the prompting form of `-w` hangs whenever
 * the process has a controlling terminal (remote.md §4). `security` prompts on
 * `/dev/tty` and never reads the pipe, so the write never returns. The dialog
 * upstream stops and the prompt lands in whatever terminal launched the app,
 * which is the only visible symptom. Only a process with no controlling
 * terminal falls back to stdin: that is every `.app` launched from Finder, so
 * the prompting form worked in the shipped app and hung under `bun run start`.
 * It also passed every probe, since a probe driven over ssh has no tty either.
 * The inline value leaves no prompt to route and no secret in any argv: `ps`
 * shows `security -i` and nothing more.
 */
export function storeCommand(id: string, hex: string): string {
  // -U so an existing item is updated rather than refused.
  return `add-generic-password -U -s ${quoted(KEYCHAIN_SERVICE)} -a ${quoted(id)} -l ${quoted(LABEL)} -j ${quoted(COMMENT)} -w ${quoted(hex)}`;
}

/**
 * One value as one token of that line.
 *
 * `security`'s interactive parser takes double quotes and backslash escapes,
 * measured rather than assumed. Nothing passed in today needs the escaping.
 * The service and the label are constants here, an id is a UUID, and the value
 * is hex. The quoting lives here anyway rather than in each caller. A newline
 * is not handled: none of those four values can contain one, the command is a
 * single line, and `security` has no escape that would keep it one.
 */
function quoted(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

// --- the keychain, and the file ----------------------------------------------

/**
 * Store one connection's password, replacing whatever was there.
 *
 * The command goes in on stdin rather than in the argv. `security`'s own usage
 * text calls the argument form insecure, and an argv is the wrong place for a
 * secret even when the kernel keeps other users out of it (the rule remote.md
 * §10 applies to profiles). The whole command goes down the pipe rather than
 * the value alone, for the reason `storeCommand` gives.
 *
 * The write is read back before this reports success. `security` exits 0 for
 * failures it merely prints, and a keychain it could not open is one. Its exit
 * code is not evidence on its own, and a password that was never written would
 * reach the user as a server rejecting a credential they can see is right.
 */
export async function storePassword(id: string, password: string): Promise<{ ok: boolean; error: string }> {
  const hex = toHex(password);
  try {
    const write = Bun.spawn([SECURITY_PATH, "-i"], {
      stdin: "pipe",
      stdout: "ignore",
      stderr: "ignore",
    });
    write.stdin.write(`${storeCommand(id, hex)}\n`);
    await write.stdin.end();
    if ((await write.exited) !== 0) return { ok: false, error: KEYCHAIN_REFUSED };
  } catch (err) {
    return { ok: false, error: `Could not reach the keychain (${reason(err)}).` };
  }
  const stored = await readPassword(id);
  if (stored !== password) return { ok: false, error: KEYCHAIN_REFUSED };
  return { ok: true, error: "" };
}

/** Whether a password is stored for this connection, without reading it. No
 * `-w`, so `security` prints the item's attributes and never its data. Asking
 * whether one exists must not be a way to obtain one. */
export async function hasPassword(id: string): Promise<boolean> {
  try {
    const p = Bun.spawn([SECURITY_PATH, "find-generic-password", "-s", KEYCHAIN_SERVICE, "-a", id], {
      stdout: "ignore",
      stderr: "ignore",
    });
    return (await p.exited) === 0;
  } catch {
    return false;
  }
}

/**
 * Drop a connection's password, if it has one.
 *
 * Silent about a missing item, because every caller is removing or re-keying a
 * connection and "there was nothing to delete" is a success for both.
 */
export async function forgetPassword(id: string): Promise<void> {
  try {
    const p = Bun.spawn([SECURITY_PATH, "delete-generic-password", "-s", KEYCHAIN_SERVICE, "-a", id], {
      stdout: "ignore",
      stderr: "ignore",
    });
    await p.exited;
  } catch {
    // A keychain that cannot be reached costs a stale item, not the removal of
    // the connection the caller is in the middle of.
  }
}

/**
 * Replace what is stored for a connection, and hand back the way to put the
 * old value back.
 *
 * `next` is a password to store, or null to leave nothing stored. The caller
 * dials between the two. The dial is what proves a password works, so the new
 * one has to be in the keychain before ssh runs. A dial that fails needs the
 * previous state back exactly.
 *
 * This is the only place in the app that reads a stored password into memory
 * for anything but checking a write, and `restore` is the reason (remote.md
 * §4). Without the old value there is no undo, and an edit that mistyped a
 * password would destroy the working one while reporting the failure. The
 * plaintext is the user's own secret, in the user's own process, held for as
 * long as one ssh takes to fail.
 */
export async function swapPassword(
  id: string,
  next: string | null,
): Promise<{ error: string; restore: () => Promise<void> }> {
  const before = (await hasPassword(id)) ? await readPassword(id) : null;
  const restore = async (): Promise<void> => {
    if (before === null) await forgetPassword(id);
    else await storePassword(id, before);
  };
  if (next === null) {
    await forgetPassword(id);
    return { error: "", restore };
  }
  const stored = await storePassword(id, next);
  // Nothing was replaced when the write failed, so there is nothing to undo. A
  // restore that rewrote the old value would be a second write to a keychain
  // that just refused one.
  if (!stored.ok) return { error: stored.error, restore: async () => {} };
  return { error: "", restore };
}

/**
 * Write the helper into the client home and return its path.
 *
 * The caller runs this before every password dial (index.ts), so a script left
 * by an older version is replaced rather than trusted. Mode 0700 keeps it
 * executable by this user alone. The write goes through a temp file and a
 * rename, like every other write in the app home, so ssh never finds a
 * half-written script.
 */
export async function ensureAskpass(): Promise<string> {
  await ensureClientHome();
  const tmp = `${ASKPASS_PATH}.tmp-${process.pid}`;
  try {
    await writeFile(tmp, askpassScript(), "utf8");
    await chmod(tmp, 0o700);
    await rename(tmp, ASKPASS_PATH);
  } catch (err) {
    await unlink(tmp).catch(() => {});
    throw err;
  }
  return ASKPASS_PATH;
}

// --- inside -------------------------------------------------------------------

const KEYCHAIN_REFUSED = "The keychain would not store that password.";

/** The only read of a stored password here. `storePassword` checks its own
 * write with it, and `swapPassword` takes the old value to restore. */
async function readPassword(id: string): Promise<string | null> {
  try {
    const p = Bun.spawn([SECURITY_PATH, "find-generic-password", "-s", KEYCHAIN_SERVICE, "-a", id, "-w"], {
      stdout: "pipe",
      stderr: "ignore",
    });
    const out = await new Response(p.stdout).text();
    if ((await p.exited) !== 0) return null;
    return fromHex(out.trim());
  } catch {
    return null;
  }
}

function reason(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}
