// Windows Credential Manager, through advapi32 (remote.md §4). Windows has no
// command-line client that can read a stored password back (`cmdkey` only
// lists and writes), so this process writes and deletes with bun:ffi, and the
// read is the generated askpass.js that ssh runs (`askpassJs`). Every item is a
// generic credential that Credential Manager lists under Windows Credentials.
import { dlopen, FFIType, ptr } from "bun:ffi";

const CRED_TYPE_GENERIC = 1;
const CRED_PERSIST_LOCAL_MACHINE = 2;

// CREDENTIALW on x64: offsets of the fields written here, and its size.
const TYPE = 4;
const TARGET_NAME = 8;
const COMMENT = 16;
const BLOB_SIZE = 32;
const BLOB = 40;
const PERSIST = 48;
const USER_NAME = 72;
const CREDENTIAL_SIZE = 80;

/** A string as the NUL-terminated UTF-16 a W function takes. */
function wide(text: string): Buffer {
  return Buffer.from(`${text}\0`, "utf16le");
}

let advapi: ReturnType<typeof openAdvapi> | null = null;

// Opened on first use: advapi32.dll exists only on Windows, and this module is
// imported on every platform.
function openAdvapi() {
  return dlopen("advapi32.dll", {
    CredWriteW: { args: [FFIType.ptr, FFIType.u32], returns: FFIType.i32 },
    CredDeleteW: { args: [FFIType.ptr, FFIType.u32, FFIType.u32], returns: FFIType.i32 },
  }).symbols;
}

/** Stores `secret` under `target`, replacing any item there. The blob is the
 * secret's UTF-16 bytes, the form `cmdkey` and the Credential Manager UI write.
 * False when Windows refused. */
export function writeCredential(target: string, user: string, comment: string, secret: string): boolean {
  advapi ??= openAdvapi();
  const targetW = wide(target);
  const userW = wide(user);
  const commentW = wide(comment);
  const blob = Buffer.from(secret, "utf16le");
  const cred = Buffer.alloc(CREDENTIAL_SIZE);
  cred.writeUInt32LE(CRED_TYPE_GENERIC, TYPE);
  cred.writeBigUInt64LE(BigInt(ptr(targetW)), TARGET_NAME);
  cred.writeBigUInt64LE(BigInt(ptr(commentW)), COMMENT);
  cred.writeUInt32LE(blob.length, BLOB_SIZE);
  cred.writeBigUInt64LE(BigInt(ptr(blob)), BLOB);
  cred.writeUInt32LE(CRED_PERSIST_LOCAL_MACHINE, PERSIST);
  cred.writeBigUInt64LE(BigInt(ptr(userW)), USER_NAME);
  return advapi.CredWriteW(ptr(cred), 0) !== 0;
}

/** Deletes the item under `target`. Silent when there is none. */
export function deleteCredential(target: string): void {
  advapi ??= openAdvapi();
  advapi.CredDeleteW(ptr(wide(target)), CRED_TYPE_GENERIC, 0);
}

/**
 * The askpass program for Windows, as JavaScript for the app's own bun.exe.
 * It reads the item named by `prefix` plus the account in `accountEnv`, prints
 * the password with no newline, and exits 1 with nothing printed when there is
 * no item. CredReadW's CREDENTIALW is read at the offsets `writeCredential`
 * writes.
 */
export function askpassJs(prefix: string, accountEnv: string): string {
  return `// Ledge's SSH_ASKPASS helper for Windows. Generated by src/bun/secrets.ts;
// edits are lost at the next password dial. What it is for:
// docs/contributor/remote.md §4.
import { dlopen, FFIType, ptr, read, toArrayBuffer } from "bun:ffi";
const account = process.env[${JSON.stringify(accountEnv)}];
if (!account) process.exit(1);
const { symbols } = dlopen("advapi32.dll", {
  CredReadW: { args: [FFIType.ptr, FFIType.u32, FFIType.u32, FFIType.ptr], returns: FFIType.i32 },
  CredFree: { args: [FFIType.ptr], returns: FFIType.void },
});
const target = Buffer.from(${JSON.stringify(prefix)} + account + "\\0", "utf16le");
const out = new BigUint64Array(1);
if (!symbols.CredReadW(ptr(target), ${CRED_TYPE_GENERIC}, 0, ptr(out))) process.exit(1);
const cred = Number(out[0]);
const size = read.u32(cred, ${BLOB_SIZE});
const secret = size > 0 ? Buffer.from(toArrayBuffer(read.ptr(cred, ${BLOB}), 0, size)).toString("utf16le") : "";
symbols.CredFree(cred);
if (!secret) process.exit(1);
process.stdout.write(secret);
`;
}
